# Nome do projeto
spring.application.name=Sistema_Biblioteca

# url do banco Postgres Local
spring.datasource.url=jdbc:postgresql://localhost:5432/sistemabiblioteca

# O usuário padrão do PostgreSQL é "postgres"
spring.datasource.username=postgres

# A senha que você definir no seu banco/Docker. Se não tiver senha, deixe em branco ou mude para a sua.
spring.datasource.password=root

# Hibernate DDL-Auto: Mantido como "update".
# Isso faz o Spring Data JPA criar ou atualizar as tabelas automaticamente no Postgres para você.
spring.jpa.hibernate.ddl-auto=update

# Mostra no console/terminal do IntelliJ os comandos SQL reais que o Spring está gerando debaixo dos panos.
spring.jpa.show-sql=true

#  Informa ao Hibernate/JPA que ele deve traduzir as queries automáticas
# do Java especificamente para a sintaxe e funções nativas do PostgreSQL.
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Permite que formulários HTML antigos usem métodos como PUT e DELETE (bom manter ativo para o Integrante C).
spring.mvc.hiddenmethod.filter.enabled=true