-- CREATE DATABASE sistemabiblioteca;

CREATE TABLE aluno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    ra VARCHAR(255) NOT NULL UNIQUE,
    possui_debito BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE livro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    isbn VARCHAR(255) UNIQUE,
    prazo_devolucao_dias INTEGER NOT NULL,
    reservado BOOLEAN NOT NULL DEFAULT FALSE,
    disponivel BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE emprestimo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id BIGINT NOT NULL,
    data_emprestimo DATE NOT NULL DEFAULT CURRENT_DATE,
    data_prevista_devolucao DATE,
    data_devolucao_efetiva DATE,
    status VARCHAR(255) NOT NULL DEFAULT 'ATIVO',
    CONSTRAINT fk_emprestimo_aluno
        FOREIGN KEY (aluno_id)
        REFERENCES aluno (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE emprestimo_livro (
    emprestimo_id BIGINT NOT NULL,
    livro_id BIGINT NOT NULL,
    PRIMARY KEY (emprestimo_id, livro_id),
    CONSTRAINT fk_emprestimo_livro_emprestimo
        FOREIGN KEY (emprestimo_id)
        REFERENCES emprestimo (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_emprestimo_livro_livro
        FOREIGN KEY (livro_id)
        REFERENCES livro (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX idx_emprestimo_aluno_id ON emprestimo (aluno_id);
CREATE INDEX idx_emprestimo_livro_livro_id ON emprestimo_livro (livro_id);